language: node_js
node_js:
  - 6
cache:
  directories:
  - global-cli/node_modules
  - node_modules
script: 
  - npm run build
branches:
  only:
  - master
deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY # declared in Travis repo settings
  secret_access_key: $AWS_SECRET_KEY
  bucket: "aucklandelections.nz"
  skip_cleanup: true
  region: ap-southeast-2
  local-dir: dist
  acl: public_read
